Adapt Examples sections to be multiline for mkdocs
CyberAlpaca/squish-api-python-extension pull request #34
Opened 2023-06-20 13:37 UTC by EduardKaverinskyi

Changes:
- Rename Example to Examples for all Example sections. This is required for mkdocs to display multi-line examples correctly.
- Add the >>> to each line in the Examples. It forces mkdocs to not squash examples into one line.

2023-06-26 21:17 UTC, Adakar reviewed
For two or more independent examples  using `>>>` seems to be ok but for for code blocks like  sections I'd prefer to see [Python code blocks](https://github.com/mkdocstrings/pytkdocs/pull/35#issuecomment-634530280) - that seems to be supported by mkdocs as well

2023-06-30 22:36 UTC, Adakar requested changes
https://github.com/CyberAlpaca/squish-api-python-extension/pull/34#pullrequestreview-1499449318

2023-07-05 13:55 UTC, pawtom approved these changes

2023-07-10 07:03 UTC, Adakar approved these changes

2023-07-12 03:58 UTC, merged